---
- name: make dockers
  hosts: localhost

  tasks:
    - name: install docker-py
      pip:
        name: docker-py
        executable: /usr/local/bin/pip3.6

    - name: make dockers
      docker_container:
        image: busybox
        command: sleep 1d
        name: "busy{{ item }}"
      with_sequence: count=3