---
- name: Deploy
  hosts: all
  serial: 1


  tasks:
    - name: disable node
      debug:
        msg: "disable {{ inventory_hostname }}"
      delegate_to: "{{ groups['uio'][0]}}"

    - name: upgrade web
      debug:
        msg: "upgrade software"