- name: Ensure .ssh directory exists.
  file: 
    dest: "/home/ubuntu/.ssh"
    mode: 0700 
    owner: ubuntu 
    state: directory
- name: Install ssh key
  copy: 
    src: "files/ssh_key_personal_website" 
    dest: "/home/ubuntu/.ssh/id_rsa"
    mode: 0600
    owner: ubuntu